export const EmptyToken = {
    at: '',
    balancePlanck: '0',
    creationBlock: 0,
    creator: '',
    desc: '',
    donationCount: '0',
    donationPlanck: '0',
    img: '',
    isActive: false,
    minActivationPlanck: '0',
    name: '',
    owner: '',
    repo: '',
    status: '',
    tags: [],
    version: 0,
}
